### ISSUE TITLE
Any real deployment?

### ISSUE THREAD

**Issue by dumblob** [gnur/tobab#3]
Interesting project! Do you have any instances deployed in "production"? Is it among the goals to have relases production-ready?

**Comment by gnur** [comment]
I have it running in my homelab for about a week now and it seems to be working pretty well. 

It's meant for homelab use, there is no plans to add any kind of high availability or redundancy. So "production" use is ofcourse relative, but I wouldn't recommend using this for any professional workload.

**Comment by dumblob** [comment]
Thanks for clarification - will see whether it'll suit my needs :wink:.
