### ISSUE TITLE
Example config does not validate

### ISSUE THREAD

**Issue by mintktkr** [gnur/tobab#4]
Hello!

I tried to deploy using the example config provided in the Readme, but when validating it, it expects a `AdminGlobs` and a `Salt` value. I added a salt to the tobab.toml file but for AdminGlobs I don't know what it is expecting.

Is there any working config example or documentation about it?

Thank you.

**Comment by gnur** [comment]
Good point, I'll have to update the docs since I changed quite some config parameters.

Thanks!
